### ISSUE TITLE
org.peimari.gleaflet.client.ILayer cannot be resolved

### ISSUE THREAD

**Issue by wassimz** [mstahv/v-leaflet-heat#2]
I have tried to integrate this addon into my project and I faced some issues. First I have fixed the issue #1 by changing the import then when I compile again it said:

**org.peimari.gleaflet.client.ILayer cannot be resolved**

Note that I have update the pom version to use the latest g-leaflet and v-leaflet package and vaadin 7.5.7.

Any help or hints ??

**Comment by wassimz** [comment]
Hi,

I have recompiled the g-leaflet-heat with the latest g-leafelt support and change the **ILayer** support with the new **Layer** class. Now it is compiling without any error. I will try to test and if everything works I will create a patch for this fix.

Thanks

**Comment by mstahv** [comment]
Hi, did you find any serious issues with 1.0 update? If it works, I don't see why we wouldn't create a new release against 1.0 series soon.

**Comment by wassimz** [comment]
Currently just fixing this import and the plugins works fine. Just when displaying the heat layer and doing zoom action it does not animate smoothly but I think this is related to the initial js plugin.

**Comment by mstahv** [comment]
The 0.4 version and onwards is now compiled against v-leaflet 1.0 .
